-- [VERSION: 1] [CONNECTION: __mfx]
CREATE TABLE IF NOT EXISTS `__MFX_USERS_TABLE_NAME__` (
	`__MFX_USER_ID_FIELD_NAME__` INT UNSIGNED NOT NULL AUTO_INCREMENT, 
	`user_name` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, 
	`user_password` BINARY(32) NULL DEFAULT NULL, 
	`user_created` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY  (`__MFX_USER_ID_FIELD_NAME__`), 
	UNIQUE  (`user_name`)
);